Controllers/ActorController.cs
using JK2247A5.Data;
using JK2247A5.Models;
using JK2247A5;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JK2247A5.Controllers
{
    public class ActorController : Controller
    {
        // Reference to the data manager
        private Manager m = new Manager();

        // GET: Actor
        public ActionResult Index()
        {
            return View(m.ActorGetAll());
        }

        // GET: Actor/Details/5
        public ActionResult Details(int? id)
        {
            // Attempt to get the matching object
            var theActor = m.ActorGetByIdWithShowInfo(id.GetValueOrDefault());

            if (theActor == null)
            {
                return HttpNotFound();
            }
            else
            {
                // Pass the object to the view
                return View(theActor);
            }
        }

        // GET: Actor/Create
        [Authorize(Roles = "Executive")]
        public ActionResult Create()
        {
            var model = new ActorAddViewModel();
            return View(model);
        }

        // POST: Actor/Create
        [HttpPost, Authorize(Roles = "Executive"), ValidateInput(false)]
        public ActionResult Create(ActorAddViewModel newItem)
        {
            
            // Validate the input
            if (!ModelState.IsValid)
            {
                return View(newItem);
            }

            // Process the input
            var addedItem = m.ActorAdd(newItem);

            if (addedItem == null)
            {
                return View(newItem);
            }
            else
            {
                return RedirectToAction("details", new { id = addedItem.Id });
            }
        }

        // GET: Actors/5/AddShow
        // TODO: 17 - Used "attribute routing" for a custom URL segment (resource)
        [Route("Actors/{id}/AddShow"), Authorize(Roles = "Coordinator")]
        public ActionResult AddShow(int id)
        {
            // Attempt to get the associated object
            var actor = m.ActorGetByIdWithShowInfo(id);

            var genres = m.GenreGetAll();
            var preSelectedGenre = genres.ElementAt(0).Id;

            if (actor == null)
            {
                return HttpNotFound();
            }
            else
            {        
                // Create and configure a form object
                var formModel = new ShowAddFormViewModel();
                formModel.ActorId = actor.Id;
                formModel.ActorName = actor.Name;

                // Get all actors and preselect the known actor
                 var selectedValues = new List<int> { actor.Id };

                formModel.ActorList = new MultiSelectList
                    (items: m.ActorGetAll(),
                    dataValueField: "Id",
                    dataTextField: "Name",
                    selectedValues: selectedValues);

                // formModel.GenreId = preSelectedGenre;
                formModel.GenreList = new SelectList(m.GenreGetAll(), "Name", "Name", selectedValue: preSelectedGenre);
                // IEnumerable<string> genres1 = m.GenreGetAll().Select(m => m.Name);
                // formModel.GenreList = new SelectList(genres1);

                return View(formModel);
            }
        }

        // POST: Actors/5/AddShow
        // TODO: 19 - Used "attribute routing" for a custom URL segment (resource)
        [Route("Actors/{id}/AddShow"), Authorize(Roles = "Coordinator"), ValidateInput(false)]
        [HttpPost]
        public ActionResult AddShow(ShowAddViewModel newItem)
        {   
            // Validate the input
            if (!ModelState.IsValid)
            {
                return View(newItem);
            }

            // Process the input
            var addedItem = m.ShowAdd(newItem);

            if (addedItem == null)
            {
                return View(newItem);
            }
            else
            {
                // TODO: 20 - Must redirect to the Vehicles controller
                return RedirectToAction("details", "show", new { id = addedItem.Id });
            }
        }




    }
}

Controllers/GenreController.cs
using JK2247A5;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JK2247A5.Controllers
{
    public class GenreController : Controller
    {
        // Reference to the data manager
        private Manager m = new Manager();

        // GET: Genre
        public ActionResult Index()
        {
            return View(m.GenreGetAll());
        }
    }
}

Controllers/LoadDataController.cs
using JK2247A5;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JK2247A5.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LoadDataController : Controller
    {

        // Reference to the manager object
        Manager m = new Manager();

        // GET: LoadData/Roles
        [AllowAnonymous]
        public ActionResult Roles()
        {
            ViewBag.Result = m.LoadRoles() ? "Roles data was loaded" : "(done)";
            return View("result");
        }

        // GET: LoadData/Genres
        public ActionResult Genres()
        {
            ViewBag.Result = m.LoadGenres() ? "Genres data was loaded" : "(done)";
            return View("result");
        }

        // GET: LoadData/Actors
        public ActionResult Actors()
        {
            ViewBag.Result = m.LoadActors() ? "Actors data was loaded" : "(done)";
            return View("result");
        }

        // GET: LoadData/Shows
        public ActionResult Shows()
        {
            ViewBag.Result = m.LoadShows() ? "Shows data was loaded" : "(done)";
            return View("result");
        }

        // GET: LoadData/Episodes
        public ActionResult Episodes()
        {
            ViewBag.Result = m.LoadEpisodes() ? "Episodes data was loaded" : "(done)";
            return View("result");
        }

        // GET: LoadData/RemoveRoles
        public ActionResult RemoveRoles()
        {
            if (m.RemoveRoles())
            {
                return Content("Roles has been removed");
            }
            else
            {
                return Content("could not remove Roles");
            }
        }

        // GET: LoadData/RemoveGenres
        public ActionResult RemoveGenres()
        {
            if (m.RemoveGenres())
            {
                return Content("Genres has been removed");
            }
            else
            {
                return Content("could not remove Genres");
            }
        }

        // GET: LoadData/RemoveActors
        public ActionResult RemoveActors()
        {
            if (m.RemoveActors())
            {
                return Content("Actors has been removed");
            }
            else
            {
                return Content("could not remove Actors");
            }
        }

        // GET: LoadData/RemoveShows
        public ActionResult RemoveShows()
        {
            if (m.RemoveShows())
            {
                return Content("Shows has been removed");
            }
            else
            {
                return Content("could not remove Shows");
            }
        }

        // GET: LoadData/RemoveEpisodes
        public ActionResult RemoveEpisodes()
        {
            if (m.RemoveEpisodes())
            {
                return Content("Episodes has been removed");
            }
            else
            {
                return Content("could not remove Episodes");
            }
        }

        // GET: LoadData/RemoveDatabase
        public ActionResult RemoveDatabase()
        {
            if (m.RemoveDatabase())
            {
                return Content("database has been removed");
            }
            else
            {
                return Content("could not remove database");
            }
        }

    }
}

Controllers/ShowController.cs
using JK2247A5.Models;
using JK2247A5;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JK2247A5.Controllers
{
    public class ShowController : Controller
    {
        // Reference to the data manager
        private Manager m = new Manager();

        // GET: Show
        public ActionResult Index()
        {
            return View(m.ShowGetAll());
        }

        // GET: Show/Details/5
        public ActionResult Details(int? id)
        {
            // Attempt to get the matching object
            var theShow = m.ShowGetByIdWithInfo(id.GetValueOrDefault());

            if (theShow == null)
            {
                return HttpNotFound();
            }
            else
            {
                // Pass the object to the view
                return View(theShow);
            }
        }

        // GET: Episodes/5/AddEpisode
        // Used "attribute routing" for a custom URL segment (resource)
        [Route("Shows/{id}/AddEpisode"), Authorize(Roles = "Clerk")]
        public ActionResult AddEpisode(int id)
        {
            // Attempt to get the associated object
            var show = m.ShowGetByIdWithInfo(id);

            var genres = m.GenreGetAll();
            var preSelectedGenre = genres.ElementAt(0).Id;

            if (show == null)
            {
                return HttpNotFound();
            }
            else
            {
                // TODO: 18 - Add Episode for a known Show
                // We send the show identifier to the form
                // There, it is hidden... <input type=hidden
                // We also pass on the name, so that the browser user
                // knows which show they're working with

                // Create and configure a form object
                var formModel = new EpisodeAddFormViewModel();
                formModel.ShowId = show.Id;
                formModel.ShowName = show.Name;

                //formModel.GenreId = preSelectedGenre;
                formModel.GenreList = new SelectList(m.GenreGetAll(), "Name", "Name", selectedValue: preSelectedGenre);
                //IEnumerable<string> genres1 = m.GenreGetAll().Select(m => m.Name);
                //formModel.GenreList = new SelectList(genres1);
                return View(formModel);
            }
        }

        // POST: Episodes/5/AddEpisode
        // Used "attribute routing" for a custom URL segment (resource)
        [Route("Shows/{id}/AddEpisode"), Authorize(Roles = "Clerk"), ValidateInput(false)]
        [HttpPost]
        public ActionResult AddEpisode(EpisodeAddViewModel newItem)
        {
            // Validate the input
            if (!ModelState.IsValid)
            {
                return View(newItem);
            }

            // Process the input
            var addedItem = m.EpisodeAdd(newItem);

            if (addedItem == null)
            {
                return View(newItem);
            }
            else
            {
                // TODO: 20 - Must redirect to the Vehicles controller
                return RedirectToAction("Details", "Episode", new { id = addedItem.Id });
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - JK2247A5</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="AAS2237A6" />
    <meta name="application-name" content="2237-0cb84679-1cb9-400b-b700-ebcc80d36e30" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Show Biz", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Genres", "Index", "Genre", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Actors", "Index", "Actor", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Shows", "Index", "Show", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Episodes", "Index", "Episode", new { area = "" }, new { @class = "nav-link" })</li>

                    <li class="dropdown nav-item">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Load Data
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark">
                            <li>@Html.ActionLink("Roles", "Roles", "LoadData", new { area = "" }, new { @class = "nav-link" })</li>

                            @using System.Security.Claims;
                            @if ((User as ClaimsPrincipal).HasClaim(ClaimTypes.Role, "Admin"))
                            {
                                <li>@Html.ActionLink("Genres", "Genres", "LoadData", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Actors", "Actors", "LoadData", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Shows", "Shows", "LoadData", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Episodes", "Episodes", "LoadData", new { area = "" }, new { @class = "nav-link" })</li>
                            }
                        </ul>
                    </li>

                </ul>
                 @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>
                <small>
                    By submitting this assignment you agree to the following:
                    I declare that this assignment is my own work in accordance with the Seneca Academic
                    Policy. No part of this assignment has been copied manually or electronically from
                    any other source (including web sites) or distributed to other students.
                </small>
            </p>
            <p>&copy; Jiyoon Kim, jkim627@myseneca.ca, WEB524, Fall $2024$</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("https://unpkg.com/@popperjs/core@2.9.3/dist/umd/popper.min.js")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>